project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Mayumi Morgan"
  date: "Date Here"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters:
      - activities/Exercise_1.qmd
      - activities/Exercise_2.qmd
      - activities/Exercise_3.qmd
      - activities/Exercise_4.qmd
      - activities/Exercise_5.qmd
      - activities/Exercise_6.qmd
      
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
